// Large dataset of sample transcripts for realistic testing

import { Transcript } from './storage';

export const sampleTranscripts: Transcript[] = [
  // CRM & Sales (15 transcripts)
  {
    id: 't1',
    expertId: 'exp-001',
    expertName: 'Maria Santos',
    expertRole: 'VP Marketing',
    topic: 'Salesforce to HubSpot migration: Common pitfalls',
    category: 'CRM Systems',
    date: '2024-11-28',
    duration: '18 min',
    content: 'The biggest mistake teams make is underestimating data mapping complexity. Historical data doesn\'t always translate cleanly between systems. Custom objects need careful planning.',
    keyInsights: [
      'Data mapping is more complex than expected',
      'Custom objects need careful planning',
      'API limitations can slow migration'
    ],
    tags: ['Salesforce', 'HubSpot', 'Migration', 'CRM'],
    upvotes: 31,
    citations: 12,
  },
  {
    id: 't2',
    expertId: 'exp-002',
    expertName: 'James Kim',
    expertRole: 'CRM Director',
    topic: 'HubSpot implementation for mid-market companies',
    category: 'CRM Systems',
    date: '2024-12-01',
    duration: '22 min',
    content: 'Mid-market companies benefit most from HubSpot\'s all-in-one approach. The key is proper onboarding and training. Most failures come from lack of adoption.',
    keyInsights: [
      'All-in-one approach works for mid-market',
      'Training is critical for adoption',
      'Start simple, expand gradually'
    ],
    tags: ['HubSpot', 'Implementation', 'Mid-market', 'CRM'],
    upvotes: 28,
    citations: 9,
  },
  {
    id: 't3',
    expertId: 'exp-003',
    expertName: 'David Chen',
    expertRole: 'Sales Operations Manager',
    topic: 'CRM data hygiene best practices',
    category: 'CRM Systems',
    date: '2024-11-15',
    duration: '15 min',
    content: 'Dirty data costs companies millions. Implement validation rules early. Regular audits are non-negotiable. Automated deduplication saves time.',
    keyInsights: [
      'Validation rules prevent bad data',
      'Regular audits are essential',
      'Automation reduces manual work'
    ],
    tags: ['CRM', 'Data Quality', 'Operations'],
    upvotes: 45,
    citations: 18,
  },
  {
    id: 't4',
    expertId: 'exp-004',
    expertName: 'Rachel Thompson',
    expertRole: 'VP Sales',
    topic: 'Sales pipeline management in Salesforce',
    category: 'CRM Systems',
    date: '2024-12-05',
    duration: '20 min',
    content: 'Pipeline hygiene directly impacts forecast accuracy. Weekly reviews with sales teams keep deals moving. Stage definitions must be crystal clear.',
    keyInsights: [
      'Pipeline reviews improve accuracy',
      'Clear stage definitions are critical',
      'Sales team alignment is key'
    ],
    tags: ['Salesforce', 'Sales Pipeline', 'Forecasting'],
    upvotes: 38,
    citations: 14,
  },
  {
    id: 't5',
    expertId: 'exp-005',
    expertName: 'Mike Rodriguez',
    expertRole: 'RevOps Director',
    topic: 'Integrating CRM with marketing automation',
    category: 'CRM Systems',
    date: '2024-11-20',
    duration: '25 min',
    content: 'Marketing and sales alignment starts with data integration. Lead scoring models need constant refinement. Attribution is the hardest problem to solve.',
    keyInsights: [
      'Data integration enables alignment',
      'Lead scoring requires iteration',
      'Attribution remains challenging'
    ],
    tags: ['CRM', 'Marketing Automation', 'Integration'],
    upvotes: 42,
    citations: 16,
  },

  // SaaS Pricing (15 transcripts)
  {
    id: 't6',
    expertId: 'exp-006',
    expertName: 'Sarah Martinez',
    expertRole: 'VP Product',
    topic: 'Usage-based pricing strategies for SaaS products',
    category: 'SaaS Pricing',
    date: '2024-12-05',
    duration: '25 min',
    content: 'Usage-based pricing works best when the value metric directly correlates to customer success. For example, charging per API call makes sense if API usage drives customer ROI.',
    keyInsights: [
      'Value metric must align with customer success',
      'Predictability matters for enterprise buyers',
      'Hybrid models reduce adoption friction'
    ],
    tags: ['Pricing', 'SaaS', 'Usage-based', 'Revenue'],
    upvotes: 42,
    citations: 15,
  },
  {
    id: 't7',
    expertId: 'exp-007',
    expertName: 'Tom Anderson',
    expertRole: 'Chief Revenue Officer',
    topic: 'Transitioning from tiered to usage-based pricing',
    category: 'SaaS Pricing',
    date: '2024-11-25',
    duration: '19 min',
    content: 'The transition is risky but can unlock growth. Grandfather existing customers carefully. Usage tracking infrastructure must be bulletproof.',
    keyInsights: [
      'Grandfather existing customers',
      'Infrastructure must be reliable',
      'Communicate changes early'
    ],
    tags: ['Pricing', 'SaaS', 'Transition', 'Revenue'],
    upvotes: 36,
    citations: 11,
  },
  {
    id: 't8',
    expertId: 'exp-008',
    expertName: 'Lisa Park',
    expertRole: 'VP Finance',
    topic: 'SaaS pricing psychology and anchoring',
    category: 'SaaS Pricing',
    date: '2024-12-10',
    duration: '17 min',
    content: 'Anchoring your highest tier changes how customers perceive value. Most buyers choose the middle option. Test pricing with real customers, not surveys.',
    keyInsights: [
      'Anchoring influences perception',
      'Middle tier is most popular',
      'Real testing beats surveys'
    ],
    tags: ['Pricing', 'Psychology', 'SaaS'],
    upvotes: 51,
    citations: 22,
  },
  {
    id: 't9',
    expertId: 'exp-009',
    expertName: 'Kevin Wu',
    expertRole: 'Product Marketing Director',
    topic: 'Freemium vs free trial: Which converts better?',
    category: 'SaaS Pricing',
    date: '2024-11-18',
    duration: '21 min',
    content: 'Free trials convert better for complex products. Freemium works for viral, simple tools. The decision depends on your sales motion and product complexity.',
    keyInsights: [
      'Complex products need free trials',
      'Freemium enables viral growth',
      'Match model to sales motion'
    ],
    tags: ['Freemium', 'Free Trial', 'Conversion', 'SaaS'],
    upvotes: 44,
    citations: 17,
  },
  {
    id: 't10',
    expertId: 'exp-010',
    expertName: 'Emma Johnson',
    expertRole: 'VP Revenue',
    topic: 'Annual vs monthly pricing strategies',
    category: 'SaaS Pricing',
    date: '2024-12-03',
    duration: '16 min',
    content: 'Annual commitments improve cash flow but reduce flexibility for customers. Offer meaningful discounts for annual plans. Monthly builds trust with smaller customers.',
    keyInsights: [
      'Annual improves cash flow',
      'Discounts must be meaningful',
      'Monthly lowers barrier to entry'
    ],
    tags: ['Pricing', 'SaaS', 'Annual Plans'],
    upvotes: 39,
    citations: 13,
  },

  // Data Infrastructure (15 transcripts)
  {
    id: 't11',
    expertId: 'exp-011',
    expertName: 'Alex Rodriguez',
    expertRole: 'VP Data Engineering',
    topic: 'Databricks vs Snowflake: Cost considerations at scale',
    category: 'Data Infrastructure',
    date: '2024-12-10',
    duration: '22 min',
    content: 'Cost overruns became an issue at 50+ TB scale. We saw Databricks pricing become unpredictable with auto-scaling, while Snowflake offered more consistent per-query costs.',
    keyInsights: [
      'Cost overruns at 50+ TB scale',
      'Auto-scaling pricing unpredictability',
      'Query-based pricing more transparent'
    ],
    tags: ['Databricks', 'Snowflake', 'Cost Management', 'Data Warehouse'],
    upvotes: 23,
    citations: 8,
  },
  {
    id: 't12',
    expertId: 'exp-012',
    expertName: 'Priya Patel',
    expertRole: 'Data Platform Lead',
    topic: 'Building a modern data stack from scratch',
    category: 'Data Infrastructure',
    date: '2024-11-22',
    duration: '28 min',
    content: 'Start with your use cases, not the tools. Data warehouse first, then ETL, then BI. Over-engineering early is the biggest mistake teams make.',
    keyInsights: [
      'Use cases drive tool selection',
      'Build incrementally',
      'Avoid over-engineering'
    ],
    tags: ['Data Stack', 'Architecture', 'Best Practices'],
    upvotes: 47,
    citations: 19,
  },
  {
    id: 't13',
    expertId: 'exp-013',
    expertName: 'Marcus Thompson',
    expertRole: 'Chief Data Officer',
    topic: 'Data governance in fast-growing startups',
    category: 'Data Infrastructure',
    date: '2024-12-01',
    duration: '24 min',
    content: 'Governance feels like overhead until you have a data breach. Start with access controls and data classification. Automate compliance checks where possible.',
    keyInsights: [
      'Access controls are foundational',
      'Classify data by sensitivity',
      'Automate compliance'
    ],
    tags: ['Data Governance', 'Security', 'Compliance'],
    upvotes: 55,
    citations: 24,
  },
  {
    id: 't14',
    expertId: 'exp-014',
    expertName: 'Jennifer Lee',
    expertRole: 'Analytics Engineer',
    topic: 'dbt best practices for data transformation',
    category: 'Data Infrastructure',
    date: '2024-11-28',
    duration: '19 min',
    content: 'Modular models are maintainable models. Document your assumptions in schema files. Testing should be automated from day one.',
    keyInsights: [
      'Modularity improves maintainability',
      'Documentation is critical',
      'Automate testing early'
    ],
    tags: ['dbt', 'Data Transformation', 'Best Practices'],
    upvotes: 41,
    citations: 15,
  },
  {
    id: 't15',
    expertId: 'exp-015',
    expertName: 'Robert Garcia',
    expertRole: 'Data Infrastructure Architect',
    topic: 'Real-time data pipelines: Kafka vs Kinesis',
    category: 'Data Infrastructure',
    date: '2024-12-08',
    duration: '26 min',
    content: 'Kafka gives you more control but requires operational expertise. Kinesis is managed but locks you into AWS. Choose based on your team capabilities.',
    keyInsights: [
      'Kafka offers more control',
      'Kinesis reduces operational burden',
      'Team skills matter most'
    ],
    tags: ['Kafka', 'Kinesis', 'Real-time', 'Streaming'],
    upvotes: 33,
    citations: 12,
  },

  // Marketing & Growth (15 transcripts)
  {
    id: 't16',
    expertId: 'exp-016',
    expertName: 'Amanda Foster',
    expertRole: 'VP Growth',
    topic: 'Product-led growth: Getting started',
    category: 'Marketing & Growth',
    date: '2024-11-30',
    duration: '23 min',
    content: 'PLG starts with a great product experience. Remove friction from sign-up. Activation metrics matter more than sign-ups. Focus on aha moments.',
    keyInsights: [
      'Product experience is foundational',
      'Optimize for activation',
      'Identify aha moments'
    ],
    tags: ['PLG', 'Product-Led Growth', 'Activation'],
    upvotes: 48,
    citations: 20,
  },
  {
    id: 't17',
    expertId: 'exp-017',
    expertName: 'Chris Miller',
    expertRole: 'Marketing Director',
    topic: 'B2B content marketing that actually works',
    category: 'Marketing & Growth',
    date: '2024-12-04',
    duration: '20 min',
    content: 'Generic content doesn\'t convert. Write for specific buyer personas. Case studies outperform whitepapers. Distribution matters more than creation.',
    keyInsights: [
      'Target specific personas',
      'Case studies convert better',
      'Distribution > creation'
    ],
    tags: ['Content Marketing', 'B2B', 'Strategy'],
    upvotes: 52,
    citations: 21,
  },
  {
    id: 't18',
    expertId: 'exp-018',
    expertName: 'Nina Kapoor',
    expertRole: 'Head of Demand Gen',
    topic: 'Attribution modeling for B2B SaaS',
    category: 'Marketing & Growth',
    date: '2024-11-19',
    duration: '18 min',
    content: 'Multi-touch attribution is hard but necessary. First touch and last touch both miss the story. Use weighted models but don\'t over-complicate.',
    keyInsights: [
      'Multi-touch shows full journey',
      'Weighted models work best',
      'Keep it simple'
    ],
    tags: ['Attribution', 'Marketing Analytics', 'B2B'],
    upvotes: 40,
    citations: 16,
  },
  {
    id: 't19',
    expertId: 'exp-019',
    expertName: 'Tyler Jackson',
    expertRole: 'Growth Lead',
    topic: 'SEO strategy for early-stage startups',
    category: 'Marketing & Growth',
    date: '2024-12-06',
    duration: '21 min',
    content: 'Long-tail keywords are your friend early on. Create content for searcher intent, not rankings. Build authority with original research.',
    keyInsights: [
      'Focus on long-tail keywords',
      'Match searcher intent',
      'Original research builds authority'
    ],
    tags: ['SEO', 'Content', 'Startups'],
    upvotes: 37,
    citations: 14,
  },
  {
    id: 't20',
    expertId: 'exp-020',
    expertName: 'Sophie Martin',
    expertRole: 'VP Marketing',
    topic: 'Email marketing automation best practices',
    category: 'Marketing & Growth',
    date: '2024-11-26',
    duration: '17 min',
    content: 'Segmentation is the difference between spam and relevance. Behavioral triggers convert better than scheduled campaigns. Test subject lines religiously.',
    keyInsights: [
      'Segmentation drives relevance',
      'Behavioral triggers perform best',
      'Always test subject lines'
    ],
    tags: ['Email Marketing', 'Automation', 'Conversion'],
    upvotes: 43,
    citations: 18,
  },

  // Engineering & DevOps (15 transcripts)
  {
    id: 't21',
    expertId: 'exp-021',
    expertName: 'David Kumar',
    expertRole: 'VP Engineering',
    topic: 'Microservices migration: When and how',
    category: 'Engineering',
    date: '2024-12-02',
    duration: '27 min',
    content: 'Don\'t migrate to microservices until you have a clear reason. Monoliths can scale far. If you must migrate, do it incrementally with strangler pattern.',
    keyInsights: [
      'Monoliths can scale',
      'Need clear business reason',
      'Migrate incrementally'
    ],
    tags: ['Microservices', 'Architecture', 'Migration'],
    upvotes: 58,
    citations: 25,
  },
  {
    id: 't22',
    expertId: 'exp-022',
    expertName: 'Laura Singh',
    expertRole: 'DevOps Lead',
    topic: 'Kubernetes cost optimization strategies',
    category: 'Engineering',
    date: '2024-11-24',
    duration: '22 min',
    content: 'Right-sizing pods saves the most money. Use spot instances for non-critical workloads. Cluster autoscaling needs careful tuning to avoid waste.',
    keyInsights: [
      'Right-size pods first',
      'Leverage spot instances',
      'Tune autoscaling carefully'
    ],
    tags: ['Kubernetes', 'Cost Optimization', 'DevOps'],
    upvotes: 46,
    citations: 19,
  },
  {
    id: 't23',
    expertId: 'exp-023',
    expertName: 'Jason Park',
    expertRole: 'Staff Engineer',
    topic: 'API design principles for scalability',
    category: 'Engineering',
    date: '2024-12-07',
    duration: '24 min',
    content: 'REST vs GraphQL is the wrong question. Design for your clients needs. Pagination and rate limiting from day one. Versioning strategy matters.',
    keyInsights: [
      'Design for client needs',
      'Build pagination early',
      'Plan versioning strategy'
    ],
    tags: ['API Design', 'REST', 'GraphQL', 'Scalability'],
    upvotes: 51,
    citations: 22,
  },
  {
    id: 't24',
    expertId: 'exp-024',
    expertName: 'Michelle Chen',
    expertRole: 'Security Engineer',
    topic: 'Security best practices for SaaS applications',
    category: 'Engineering',
    date: '2024-11-29',
    duration: '20 min',
    content: 'Security is not a feature, it\'s a requirement. Input validation everywhere. Use established libraries for crypto. SOC 2 compliance is table stakes.',
    keyInsights: [
      'Validate all inputs',
      'Don\'t roll your own crypto',
      'SOC 2 is minimum standard'
    ],
    tags: ['Security', 'SaaS', 'Compliance'],
    upvotes: 62,
    citations: 27,
  },
  {
    id: 't25',
    expertId: 'exp-025',
    expertName: 'Eric Thompson',
    expertRole: 'CTO',
    topic: 'Technical debt management strategies',
    category: 'Engineering',
    date: '2024-12-09',
    duration: '19 min',
    content: 'Technical debt is inevitable. The question is how much you can afford. Allocate 20% of engineering time to pay it down. Track it explicitly.',
    keyInsights: [
      'Debt is inevitable',
      'Allocate 20% to paydown',
      'Track debt explicitly'
    ],
    tags: ['Technical Debt', 'Engineering Management'],
    upvotes: 54,
    citations: 23,
  },

  // Customer Success (10 transcripts)
  {
    id: 't26',
    expertId: 'exp-026',
    expertName: 'Rachel Green',
    expertRole: 'VP Customer Success',
    topic: 'Reducing churn in B2B SaaS',
    category: 'Customer Success',
    date: '2024-11-27',
    duration: '21 min',
    content: 'Churn is a lagging indicator. Focus on engagement metrics. Health scores predict churn before it happens. Proactive outreach saves accounts.',
    keyInsights: [
      'Engagement predicts churn',
      'Build health scores',
      'Be proactive'
    ],
    tags: ['Churn', 'Customer Success', 'Retention'],
    upvotes: 49,
    citations: 20,
  },
  {
    id: 't27',
    expertId: 'exp-027',
    expertName: 'Brian Wilson',
    expertRole: 'Customer Success Director',
    topic: 'Scaling customer success teams',
    category: 'Customer Success',
    date: '2024-12-05',
    duration: '18 min',
    content: 'Segment customers by ARR and potential. High-touch for enterprise, tech-touch for SMB. Automation is not impersonal if done right.',
    keyInsights: [
      'Segment by ARR and potential',
      'Match touch model to segment',
      'Automate thoughtfully'
    ],
    tags: ['Customer Success', 'Scaling', 'Operations'],
    upvotes: 44,
    citations: 17,
  },
  {
    id: 't28',
    expertId: 'exp-028',
    expertName: 'Angela Martinez',
    expertRole: 'Head of CS',
    topic: 'Customer onboarding frameworks that work',
    category: 'Customer Success',
    date: '2024-11-21',
    duration: '23 min',
    content: 'Time to value is the most important metric. Create clear milestones. Celebrate quick wins. Onboarding never really ends.',
    keyInsights: [
      'Optimize time to value',
      'Create clear milestones',
      'Celebrate wins'
    ],
    tags: ['Onboarding', 'Customer Success', 'Activation'],
    upvotes: 53,
    citations: 22,
  },
  {
    id: 't29',
    expertId: 'exp-029',
    expertName: 'Kevin O\'Brien',
    expertRole: 'VP Customer Experience',
    topic: 'NPS vs CSAT: Which metric matters?',
    category: 'Customer Success',
    date: '2024-12-03',
    duration: '16 min',
    content: 'NPS measures loyalty, CSAT measures satisfaction. Use both but don\'t obsess over scores. Follow-up conversations matter more than the number.',
    keyInsights: [
      'Different metrics, different purposes',
      'Use both strategically',
      'Conversations > scores'
    ],
    tags: ['NPS', 'CSAT', 'Customer Success'],
    upvotes: 41,
    citations: 15,
  },
  {
    id: 't30',
    expertId: 'exp-030',
    expertName: 'Samantha Lee',
    expertRole: 'Customer Success Manager',
    topic: 'Building customer advisory boards',
    category: 'Customer Success',
    date: '2024-11-25',
    duration: '19 min',
    content: 'CABs are goldmines for product feedback. Invite power users and strategic accounts. Make it exclusive. Provide real value, not just feedback sessions.',
    keyInsights: [
      'Invite strategic accounts',
      'Make it exclusive',
      'Provide real value'
    ],
    tags: ['Customer Advisory Board', 'Feedback', 'Product'],
    upvotes: 38,
    citations: 14,
  },

  // Product Management (10 transcripts)
  {
    id: 't31',
    expertId: 'exp-031',
    expertName: 'Daniel Kim',
    expertRole: 'VP Product',
    topic: 'Product roadmap prioritization frameworks',
    category: 'Product Management',
    date: '2024-12-01',
    duration: '22 min',
    content: 'RICE scoring works but don\'t trust it blindly. Strategic bets don\'t always score high. Say no more than you say yes. Communicate your decisions.',
    keyInsights: [
      'Frameworks are tools, not rules',
      'Make strategic bets',
      'Communication is key'
    ],
    tags: ['Product Management', 'Prioritization', 'Roadmap'],
    upvotes: 56,
    citations: 24,
  },
  {
    id: 't32',
    expertId: 'exp-032',
    expertName: 'Emily Rodriguez',
    expertRole: 'Senior Product Manager',
    topic: 'User research methods for B2B products',
    category: 'Product Management',
    date: '2024-11-23',
    duration: '20 min',
    content: 'B2B research is different from B2C. Talk to users and buyers separately. Jobs to be done framework reveals real needs. Watch people use your product.',
    keyInsights: [
      'Separate users from buyers',
      'JTBD reveals real needs',
      'Observe actual usage'
    ],
    tags: ['User Research', 'B2B', 'Product Management'],
    upvotes: 47,
    citations: 19,
  },
  {
    id: 't33',
    expertId: 'exp-033',
    expertName: 'Thomas Anderson',
    expertRole: 'Head of Product',
    topic: 'Product analytics: What to track',
    category: 'Product Management',
    date: '2024-12-06',
    duration: '18 min',
    content: 'Track everything is bad advice. Focus on key user journeys. Funnel analysis reveals drop-off points. Cohort analysis shows retention trends.',
    keyInsights: [
      'Focus on key journeys',
      'Use funnels for drop-offs',
      'Cohorts show retention'
    ],
    tags: ['Product Analytics', 'Metrics', 'Data'],
    upvotes: 50,
    citations: 21,
  },
  {
    id: 't34',
    expertId: 'exp-034',
    expertName: 'Jessica Wang',
    expertRole: 'Product Director',
    topic: 'Building great product teams',
    category: 'Product Management',
    date: '2024-11-28',
    duration: '24 min',
    content: 'Cross-functional teams ship better products. PM, design, engineering should be a unit. Autonomy drives motivation. Clear goals prevent chaos.',
    keyInsights: [
      'Cross-functional teams win',
      'Autonomy motivates',
      'Goals provide clarity'
    ],
    tags: ['Team Building', 'Product Management', 'Leadership'],
    upvotes: 59,
    citations: 26,
  },
  {
    id: 't35',
    expertId: 'exp-035',
    expertName: 'Alex Murphy',
    expertRole: 'Chief Product Officer',
    topic: 'Product-market fit indicators',
    category: 'Product Management',
    date: '2024-12-04',
    duration: '21 min',
    content: 'PMF is not binary, it\'s a spectrum. Organic growth is the clearest signal. High retention and NPS indicate strong fit. Revenue growth validates it.',
    keyInsights: [
      'PMF is a spectrum',
      'Organic growth signals fit',
      'Retention validates PMF'
    ],
    tags: ['Product-Market Fit', 'Startups', 'Growth'],
    upvotes: 61,
    citations: 28,
  },

  // AI & ML (5 transcripts)
  {
    id: 't36',
    expertId: 'exp-036',
    expertName: 'Dr. Sarah Johnson',
    expertRole: 'ML Engineering Lead',
    topic: 'Implementing AI features in production',
    category: 'AI & ML',
    date: '2024-12-08',
    duration: '26 min',
    content: 'Model performance in production differs from development. Monitor for drift constantly. Have fallback logic. Start with simple models.',
    keyInsights: [
      'Monitor for model drift',
      'Always have fallbacks',
      'Start simple'
    ],
    tags: ['AI', 'Machine Learning', 'Production'],
    upvotes: 52,
    citations: 23,
  },
  {
    id: 't37',
    expertId: 'exp-037',
    expertName: 'James Patterson',
    expertRole: 'Data Scientist',
    topic: 'LLM integration patterns for SaaS',
    category: 'AI & ML',
    date: '2024-12-02',
    duration: '23 min',
    content: 'LLMs are powerful but expensive. Cache aggressively. Use smaller models where possible. Prompt engineering matters more than model selection.',
    keyInsights: [
      'Caching reduces costs',
      'Right-size your models',
      'Prompts > model choice'
    ],
    tags: ['LLM', 'AI', 'SaaS', 'Integration'],
    upvotes: 48,
    citations: 20,
  },

  // Additional diverse topics (43 more to reach 80 total)
  ...generateAdditionalTranscripts(),
];

// Generate additional transcripts programmatically for variety
function generateAdditionalTranscripts(): Transcript[] {
  const expertNames = [
    'Oliver Bennett', 'Sophia Zhang', 'Lucas Morales', 'Isabella Hayes',
    'Nathan Brooks', 'Ava Sullivan', 'Ethan Wright', 'Mia Foster',
    'Ryan Mitchell', 'Olivia Carter', 'Brandon Scott', 'Emma Davis',
    'Jordan Hayes', 'Lily Turner', 'Austin Reed', 'Grace Collins',
    'Dylan Cooper', 'Zoe Phillips', 'Cameron Stewart', 'Hannah Morris',
    'Trevor Ross', 'Chloe Bennett', 'Marcus Powell', 'Aria Hughes',
    'Logan Campbell', 'Madison Bailey', 'Isaac Rivera', 'Ella Peterson',
    'Caleb Richardson', 'Nora Watson', 'Gavin Brooks', 'Scarlett Gray',
    'Xavier Price', 'Ruby Martinez', 'Owen Foster', 'Violet Cooper',
    'Dominic Reed', 'Stella Ward', 'Julian Torres', 'Aurora Barnes',
    'Sebastian Cole', 'Hazel Murphy', 'Adrian Sanders'
  ];

  const topics = [
    { category: 'CRM Systems', topic: 'Pipedrive vs Copper for small teams', role: 'Sales Director' },
    { category: 'CRM Systems', topic: 'Custom CRM development vs off-the-shelf', role: 'CTO' },
    { category: 'SaaS Pricing', topic: 'Discount strategies for annual contracts', role: 'CFO' },
    { category: 'SaaS Pricing', topic: 'Value-based pricing implementation', role: 'VP Product' },
    { category: 'Data Infrastructure', topic: 'Data lake vs data warehouse decision', role: 'Data Architect' },
    { category: 'Data Infrastructure', topic: 'Apache Airflow at scale', role: 'Data Engineer' },
    { category: 'Marketing & Growth', topic: 'Paid social vs paid search ROI', role: 'Growth Marketing Manager' },
    { category: 'Marketing & Growth', topic: 'Building a content calendar', role: 'Content Director' },
    { category: 'Engineering', topic: 'CI/CD pipeline best practices', role: 'DevOps Engineer' },
    { category: 'Engineering', topic: 'Monitoring and observability tools', role: 'Site Reliability Engineer' },
    { category: 'Customer Success', topic: 'Customer health scoring models', role: 'CS Operations Lead' },
    { category: 'Customer Success', topic: 'QBR best practices', role: 'Enterprise CSM' },
    { category: 'Product Management', topic: 'Feature flag strategies', role: 'Senior PM' },
    { category: 'Product Management', topic: 'Competitive analysis frameworks', role: 'Product Strategy Lead' },
    { category: 'CRM Systems', topic: 'Zoho CRM for growing teams', role: 'Operations Manager' },
    { category: 'CRM Systems', topic: 'CRM reporting and dashboards', role: 'Revenue Analytics Lead' },
    { category: 'SaaS Pricing', topic: 'Seat-based vs usage-based pricing', role: 'Pricing Manager' },
    { category: 'SaaS Pricing', topic: 'International pricing strategies', role: 'VP International' },
    { category: 'Data Infrastructure', topic: 'BigQuery cost optimization', role: 'Data Platform Engineer' },
    { category: 'Data Infrastructure', topic: 'Data quality frameworks', role: 'Data Quality Lead' },
    { category: 'Marketing & Growth', topic: 'Conversion rate optimization tactics', role: 'Growth Engineer' },
    { category: 'Marketing & Growth', topic: 'Brand positioning for B2B', role: 'Brand Director' },
    { category: 'Engineering', topic: 'Database migration strategies', role: 'Database Administrator' },
    { category: 'Engineering', topic: 'API rate limiting patterns', role: 'Backend Engineer' },
    { category: 'Customer Success', topic: 'Enterprise support vs self-service', role: 'Support Director' },
    { category: 'Customer Success', topic: 'Customer success metrics that matter', role: 'VP CS' },
    { category: 'Product Management', topic: 'A/B testing best practices', role: 'Growth PM' },
    { category: 'Product Management', topic: 'Product documentation strategies', role: 'Technical Writer' },
    { category: 'AI & ML', topic: 'Recommendation system implementation', role: 'ML Engineer' },
    { category: 'AI & ML', topic: 'AI ethics in product development', role: 'AI Product Lead' },
    { category: 'CRM Systems', topic: 'Mobile CRM strategies', role: 'Product Manager' },
    { category: 'SaaS Pricing', topic: 'Pricing page optimization', role: 'Conversion Specialist' },
    { category: 'Data Infrastructure', topic: 'Stream processing architectures', role: 'Streaming Data Engineer' },
    { category: 'Marketing & Growth', topic: 'Partner marketing programs', role: 'Partner Marketing Lead' },
    { category: 'Engineering', topic: 'Feature toggle management', role: 'Staff Engineer' },
    { category: 'Customer Success', topic: 'Customer education programs', role: 'Education Manager' },
    { category: 'Product Management', topic: 'Mobile app vs web prioritization', role: 'Mobile Product Lead' },
    { category: 'CRM Systems', topic: 'Sales forecasting accuracy', role: 'VP Sales Operations' },
    { category: 'SaaS Pricing', topic: 'Add-on pricing strategies', role: 'Monetization PM' },
    { category: 'Data Infrastructure', topic: 'Data mesh architecture', role: 'Enterprise Architect' },
    { category: 'Marketing & Growth', topic: 'Webinar marketing strategies', role: 'Events Manager' },
    { category: 'Engineering', topic: 'Technical debt prioritization', role: 'Engineering Manager' },
    { category: 'Customer Success', topic: 'Expansion and upsell tactics', role: 'Growth CS Manager' },
  ];

  return topics.map((t, i) => ({
    id: `t${38 + i}`,
    expertId: `exp-${38 + i}`,
    expertName: expertNames[i],
    expertRole: t.role,
    topic: t.topic,
    category: t.category,
    date: `2024-${11 + Math.floor(i / 15)}-${10 + (i % 20)}`,
    duration: `${15 + (i % 15)} min`,
    content: `Expert insights on ${t.topic.toLowerCase()}. Detailed discussion covering best practices, common pitfalls, and strategic recommendations based on years of experience.`,
    keyInsights: [
      'Key insight about implementation',
      'Strategic considerations',
      'Practical recommendations'
    ],
    tags: t.category.split(' ').concat(t.topic.split(' ').slice(0, 2)),
    upvotes: 20 + (i % 40),
    citations: 8 + (i % 20),
  }));
}
